version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: companydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      - ./php_code/init.sql:/docker-entrypoint-initdb.d/init.sql    
    ports:
      - "3306:3306"

  php:
    build: ./php_code
    container_name: php
    volumes:
      - ./php_code:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db

  nginx:
    build: ./nginx
    container_name: nginx
    volumes:
      - ./php_code:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "7777:7777"
    depends_on:
      - php

volumes:
  db_data:
